### ISSUE TITLE
Error: Invalid username

### ISSUE THREAD

**Issue by Jean85** [drone-plugins/drone-sftp#10]
I'm trying to use this plugin in my Drone build, but I'm currently having an auth issue with it. This is the `build` part of my `.drone.yml` (sensitive data redacted):

```
deploy:
  sftp:
    when:
      branch: master
    host: project.example.com
    user: project
    destination_path: /home/project
    files:
      - docker/docker-composer.yml.production

  ssh:
    when:
      branch: master
    host: project.example.com
    user: project
    commands:
      - mv -f docker-composer.yml.production docker-composer.yml
      ...
```

As you can see, I have the same config for the SFTP and SSH plugins, since I'm connecting to the same production server. I've configured Drone's repo key into the allowed keys of the server, and the SSH plugin is working perfectly fine. The SFTP one is not, this is what I get when Drone reaches that part of the build:

    [info] Pulling image plugins/drone-sftp:latest
    An error happened: Error: Invalid username
    [info] build failed (exit code 2)

Is this a bug? Or I am missing something?
