### ISSUE TITLE
Is this dead or outdated? Any alternatives?

### ISSUE THREAD

**Issue by hypervtechnics** [drone-plugins/drone-sftp#20]

**Comment by techknowlogick** [comment]
Yes, all plugins in the drone-plugins org are maintained. If you are receiving any errors using this please open an issue and we can resolve them.

**Comment by hypervtechnics** [comment]
I can't find any up-to-date usage instructions. Also this plugin is not listed on http://plugins.drone.io/

**Comment by tboerger** [comment]
This plugin is indeed outdated, but AFAIK there is an updated version available written by @appleboy

**Comment by techknowlogick** [comment]
@tboerger should this repo be archived?

**Comment by hypervtechnics** [comment]
In addition [the docker hub](https://hub.docker.com/r/plugins/drone-sftp) says its outdated and links to a "new" version which [does not exist](https://hub.docker.com/r/plugins/sftp/).

**Comment by tboerger** [comment]
Let's talk to @appleboy is he's willing to move his version into this org.

**Comment by hypervtechnics** [comment]
@tboerger The one's by @appleboy are for scp and an sftp cache.

**Comment by hypervtechnics** [comment]
@tboerger I just wrote my own which works when testing but I am unable to test in CI pipeline as I am not familiar with the deployment of plugins. How do I access my private docker registry?

**Comment by appleboy** [comment]
@hypervtechnics maybe you should try the [drone-scp](https://github.com/appleboy/drone-scp) plugin.

**Comment by techknowlogick** [comment]
Here is how to pull a private image https://discourse.drone.io/t/how-to-pull-private-images-with-1-0/3155

**Comment by techknowlogick** [comment]
I would suggest you move this discussion to https://discourse.drone.io/ so others can benefit from anything that you discover.

**Comment by hypervtechnics** [comment]
@appleboy I tried but that did not work within the given environment. The environment is a chrooted sftp server. Therefore I am unable to use SSH or execute SSH commands. Also I am then unable to use SCP. Instead plain SFTP is required. Your plugin makes use of SSH commands 😢.

@techknowlogick Where would you put this? Ideas, Development or Support? Also thank you very much for the link! 😄 

I just got the whole thing working but bypassed the drone plugin way as I can't find enough docs on how to properly make it compatible... My current way - kinda hacky - I know but it works:

```yaml
- name: deploy-staging
  image: hypervtechnics/drone-sftp
  commands:
  - dotnet /app/Drone.SFTP.dll
  environment:
    PLUGIN_HOST: staging.domain.com
    PLUGIN_USERNAME:
      from_secret: sftp_staging_username
    PLUGIN_PASSWORD:
      from_secret: sftp_staging_password
    PLUGIN_TARGET: /files/web
    PLUGIN_SOURCE: /drone/src/public
    PLUGIN_CLEAN: true
  when:
    branch:
    - develop
    event:
      exclude:
      - pull_request
```
