### ISSUE TITLE
Uploading Directories

### ISSUE THREAD

**Issue by jsonfry** [drone-plugins/drone-sftp#7]
Does this work with uploading a directory?

I'm seeing this error `An error happened: Error: ENOENT: no such file or directory, open 'classes'`. `classes` is the name of the first folder in the directory I want to upload. 

This is a reduced part of my .drone.yml

```
publish:
  sftp:
    host: ftp.example.org
    port: 22
    username: abc
    password: abc123
    files:
      - app/build/reports/tests/debug/
      (continued...)
```
