### ISSUE TITLE
glob patterns?

### ISSUE THREAD

**Issue by fommil** [drone-plugins/drone-sftp#9]
The docs don't mention glob patterns, but the `*` there does imply that it might work.

This is what I plan to do, do you think it'll work? (I'll probably have the answer by experiment by the time you read this)

```
  sftp:
    host: docs.typelevel.org
    username: typelevel
    files: 
      - target/scala-*/*-assembly.jar
```

and I'm expecting that to use the drone ssh certificate.

**Comment by fommil** [comment]
```
ls: no such file or directory: /drone/src/github.com/ensime/ensime-server/target/scala-*/*-assembly.jar
```

so I'm guessing not :cry:

**Comment by athieriot** [comment]
I've been using target/*.jar with no issue before. I wonder what is the trouble here. 

Think it's about two wildcards?

**Comment by fommil** [comment]
yeah, must be. The file is definitely there:

```
[info] Packaging /drone/src/github.com/ensime/ensime-server/target/scala-2.10/ensime_2.10-0.9.10-SNAPSHOT-assembly.jar ...
[info] Done packaging.
[success] Total time: 18 s, completed Apr 16, 2016 10:13:34 AM
[info] Pulling image plugins/drone-sftp:latest
Connection successful. 
ls: no such file or directory: /drone/src/github.com/ensime/ensime-server/target/scala-*/*-assembly.jar
```

**Comment by fommil** [comment]
I could hack it for now by hardcoding two file paths, knowing only one will come out.

**Comment by fommil** [comment]
confirmed that it's the star in the middle. This works as a hack

```
  sftp:
    host: docs.typelevel.org
    username: typelevel
    destination_path: ensime.typelevel.org/
    files: 
      - target/scala-2.10/*-assembly.jar
      - target/scala-2.11/*-assembly.jar
```

but it's a bit nasty
